# ============================================
# Streamlit Secrets Configuration
# ============================================
# IMPORTANT: 
# - Copy this file to: .streamlit/secrets.toml
# - Fill in your actual API keys and credentials
# - NEVER commit secrets.toml to Git!
# - This file is already in .gitignore
# ============================================

# ============================================
# OpenAI API Configuration
# ============================================
# Get your API key from: https://platform.openai.com/api-keys
OPENAI_API_KEY = "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
"

# ============================================
# Supabase Configuration
# ============================================
# Get your credentials from Supabase Dashboard:
# 1. Go to: https://supabase.com/dashboard
# 2. Select your project
# 3. Click Settings (gear icon) → API
# 4. Copy Project URL and anon/public key

SUPABASE_URL = "https://bgtyodovlhzlmnsbqgqk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndHlvZG92bGh6bG1uc2JxZ3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzU2NjEsImV4cCI6MjA3MzkxMTY2MX0.AXSSsCpix48Lgp8USJ8ToYGkMU7ZZVJqRD9O0vbNAkk"

# ============================================
# Optional: Application Settings
# ============================================
[settings]
default_language = "id"  # "id" for Indonesian, "en" for English
enable_ocr = false       # Enable OCR for scanned PDFs

# ============================================
# Optional: Pre-configured Roles
# ============================================
# You can pre-configure default roles here (optional)
# These will be automatically loaded on first run

# [roles]
# software_engineer = """
# Required Skills:
# - Python (3+ years)
# - Django/Flask framework
# - PostgreSQL/MySQL
# - RESTful API development
# - Git version control
# 
# Nice to have:
# - Docker/Kubernetes
# - AWS/GCP experience
# - CI/CD pipelines
# """
# 
# data_analyst = """
# Required Skills:
# - SQL expertise
# - Python (Pandas, NumPy)
# - Data visualization (Tableau/PowerBI)
# - Statistical analysis
# - Excel advanced
# 
# Nice to have:
# - Machine learning basics
# - R programming
# - Big data tools (Spark, Hadoop)
# """

# ============================================
# DEPLOYMENT INSTRUCTIONS
# ============================================
# 
# FOR LOCAL DEVELOPMENT:
# ----------------------
# 1. Create folder: .streamlit/
# 2. Copy this file to: .streamlit/secrets.toml
# 3. Replace placeholder values with your actual credentials
# 4. Run: streamlit run app_supabase.py
# 5. Credentials will be auto-loaded!
#
# FOR STREAMLIT CLOUD DEPLOYMENT:
# --------------------------------
# 1. Go to your app dashboard on https://share.streamlit.io
# 2. Click on your app
# 3. Click "Settings" (gear icon)
# 4. Click "Secrets" in the left menu
# 5. Copy and paste the content of this file
# 6. Replace placeholder values with actual credentials
# 7. Click "Save"
# 8. Redeploy your app
#
# ============================================
# SECURITY BEST PRACTICES
# ============================================
# 
# ⚠️ NEVER commit secrets.toml to Git!
# ⚠️ NEVER share your API keys publicly!
# ⚠️ Use different keys for dev/staging/production
# ⚠️ Rotate API keys regularly
# ⚠️ Monitor API usage in OpenAI and Supabase dashboards
# ⚠️ Set up billing alerts to avoid unexpected charges
#
# ============================================
# TESTING YOUR CONFIGURATION
# ============================================
# 
# After setting up secrets:
# 1. Run the app: streamlit run app_supabase.py
# 2. Check sidebar - you should see:
#    ✅ "API Key terkonfigurasi otomatis"
#    ✅ "Supabase terkonfigurasi otomatis"
# 3. If not working:
#    - Check file location: .streamlit/secrets.toml
#    - Check TOML syntax is correct
#    - Restart the Streamlit app
#    - Check logs in terminal for errors
#
# ============================================
